server:
  port: 8079

grpc:
  client:
    GRPCService:
      address: 'static://localhost:8080'
      negotiationType: PLAINTEXT
    APIService:
      address: 'static://localhost:8080'
      negotiationType: PLAINTEXT