server:
  port: 8079

grpc:
  client:
    GRPCService:
      address: 'static://192.168.202.43:8080'
      negotiationType: PLAINTEXT
    APIService:
      address: 'static://192.168.202.43:8080'
      negotiationType: PLAINTEXT