server:
  port: 8079

grpc:
  client:
    GRPCService:
      address: 'static://10.16.3.199:8080'
      negotiationType: PLAINTEXT
    APIService:
      address: 'static://10.16.3.199:8080'
      negotiationType: PLAINTEXT